name: PR Checks

on:
  pull_request:
    
jobs:
  test-flutter:
    name: Test Flutter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.1'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .

    - name: Analyze project source
      run: flutter analyze

    - name: Run tests
      run: flutter test